---

- name: "Play to Validate Devices"
  hosts: S2
  connection: network_cli

  tasks:
    - name: "Task 1 - use NAPALM validate"
      napalm_validate:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ napalm_platform }}"
        validation_file: "{{ inventory_hostname }}-facts.yml"
        password: "{{ ansible_password }}"
      register: result
      ignore_errors: yes

    - name: "Task 2 - Print the result"
      debug:
        msg: "{{ result }}"

