---
- name: "Retrieve Information using RESTCONF"
  hosts: CSR1
  connection: local
  gather_facts: false

  # vars:
  #   restconf_url: "https://{{ ansible_host }}/restconf/data/native/"
  #   accept_header: "application/yang-data+json"

  tasks:
    - name: "Query RESTCONF Endpoint for User Information"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/router"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: restconf_response

    - name: "Display Retrieved Information"
      debug:
        msg: "{{ restconf_response.json }}"
